/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CaseFitRouteImport } from './routes/case-fit'
import { Route as CodebookRouteImport } from './routes/codebook'
import { Route as LiteratureRouteImport } from './routes/literature'
import { Route as ObservatoryRouteImport } from './routes/observatory'
import { Route as TrainerRouteImport } from './routes/trainer'
import { Route as CodebookIndexRouteImport } from './routes/codebook/index'
import { Route as CodebookCodeRouteImport } from './routes/codebook/$code'
import { Route as ObservatoryIndexRouteImport } from './routes/observatory/index'
import { Route as ObservatoryIdRouteImport } from './routes/observatory/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseFitRoute = CaseFitRouteImport.update({
  id: '/case-fit',
  path: '/case-fit',
  getParentRoute: () => rootRouteImport,
} as any)
const CodebookRoute = CodebookRouteImport.update({
  id: '/codebook',
  path: '/codebook',
  getParentRoute: () => rootRouteImport,
} as any)
const LiteratureRoute = LiteratureRouteImport.update({
  id: '/literature',
  path: '/literature',
  getParentRoute: () => rootRouteImport,
} as any)
const ObservatoryRoute = ObservatoryRouteImport.update({
  id: '/observatory',
  path: '/observatory',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerRoute = TrainerRouteImport.update({
  id: '/trainer',
  path: '/trainer',
  getParentRoute: () => rootRouteImport,
} as any)
const CodebookIndexRoute = CodebookIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CodebookRoute,
} as any)
const CodebookCodeRoute = CodebookCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => CodebookRoute,
} as any)
const ObservatoryIndexRoute = ObservatoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ObservatoryRoute,
} as any)
const ObservatoryIdRoute = ObservatoryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ObservatoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/case-fit': typeof CaseFitRoute
  '/codebook': typeof CodebookRouteWithChildren
  '/literature': typeof LiteratureRoute
  '/observatory': typeof ObservatoryRouteWithChildren
  '/trainer': typeof TrainerRoute
  '/codebook/$code': typeof CodebookCodeRoute
  '/observatory/$id': typeof ObservatoryIdRoute
  '/codebook/': typeof CodebookIndexRoute
  '/observatory/': typeof ObservatoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/case-fit': typeof CaseFitRoute
  '/literature': typeof LiteratureRoute
  '/trainer': typeof TrainerRoute
  '/codebook/$code': typeof CodebookCodeRoute
  '/observatory/$id': typeof ObservatoryIdRoute
  '/codebook': typeof CodebookIndexRoute
  '/observatory': typeof ObservatoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/case-fit': typeof CaseFitRoute
  '/codebook': typeof CodebookRouteWithChildren
  '/literature': typeof LiteratureRoute
  '/observatory': typeof ObservatoryRouteWithChildren
  '/trainer': typeof TrainerRoute
  '/codebook/$code': typeof CodebookCodeRoute
  '/observatory/$id': typeof ObservatoryIdRoute
  '/codebook/': typeof CodebookIndexRoute
  '/observatory/': typeof ObservatoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/case-fit'
    | '/codebook'
    | '/literature'
    | '/observatory'
    | '/trainer'
    | '/codebook/$code'
    | '/observatory/$id'
    | '/codebook/'
    | '/observatory/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/case-fit'
    | '/literature'
    | '/trainer'
    | '/codebook/$code'
    | '/observatory/$id'
    | '/codebook'
    | '/observatory'
  id:
    | '__root__'
    | '/'
    | '/case-fit'
    | '/codebook'
    | '/literature'
    | '/observatory'
    | '/trainer'
    | '/codebook/$code'
    | '/observatory/$id'
    | '/codebook/'
    | '/observatory/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaseFitRoute: typeof CaseFitRoute
  CodebookRoute: typeof CodebookRouteWithChildren
  LiteratureRoute: typeof LiteratureRoute
  ObservatoryRoute: typeof ObservatoryRouteWithChildren
  TrainerRoute: typeof TrainerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-fit': {
      id: '/case-fit'
      path: '/case-fit'
      fullPath: '/case-fit'
      preLoaderRoute: typeof CaseFitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codebook': {
      id: '/codebook'
      path: '/codebook'
      fullPath: '/codebook'
      preLoaderRoute: typeof CodebookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/literature': {
      id: '/literature'
      path: '/literature'
      fullPath: '/literature'
      preLoaderRoute: typeof LiteratureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/observatory': {
      id: '/observatory'
      path: '/observatory'
      fullPath: '/observatory'
      preLoaderRoute: typeof ObservatoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer': {
      id: '/trainer'
      path: '/trainer'
      fullPath: '/trainer'
      preLoaderRoute: typeof TrainerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codebook/': {
      id: '/codebook/'
      path: '/'
      fullPath: '/codebook/'
      preLoaderRoute: typeof CodebookIndexRouteImport
      parentRoute: typeof CodebookRoute
    }
    '/codebook/$code': {
      id: '/codebook/$code'
      path: '/$code'
      fullPath: '/codebook/$code'
      preLoaderRoute: typeof CodebookCodeRouteImport
      parentRoute: typeof CodebookRoute
    }
    '/observatory/': {
      id: '/observatory/'
      path: '/'
      fullPath: '/observatory/'
      preLoaderRoute: typeof ObservatoryIndexRouteImport
      parentRoute: typeof ObservatoryRoute
    }
    '/observatory/$id': {
      id: '/observatory/$id'
      path: '/$id'
      fullPath: '/observatory/$id'
      preLoaderRoute: typeof ObservatoryIdRouteImport
      parentRoute: typeof ObservatoryRoute
    }
  }
}

interface CodebookRouteChildren {
  CodebookCodeRoute: typeof CodebookCodeRoute
  CodebookIndexRoute: typeof CodebookIndexRoute
}

const CodebookRouteChildren: CodebookRouteChildren = {
  CodebookCodeRoute: CodebookCodeRoute,
  CodebookIndexRoute: CodebookIndexRoute,
}

const CodebookRouteWithChildren = CodebookRoute._addFileChildren(
  CodebookRouteChildren,
)

interface ObservatoryRouteChildren {
  ObservatoryIdRoute: typeof ObservatoryIdRoute
  ObservatoryIndexRoute: typeof ObservatoryIndexRoute
}

const ObservatoryRouteChildren: ObservatoryRouteChildren = {
  ObservatoryIdRoute: ObservatoryIdRoute,
  ObservatoryIndexRoute: ObservatoryIndexRoute,
}

const ObservatoryRouteWithChildren = ObservatoryRoute._addFileChildren(
  ObservatoryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaseFitRoute: CaseFitRoute,
  CodebookRoute: CodebookRouteWithChildren,
  LiteratureRoute: LiteratureRoute,
  ObservatoryRoute: ObservatoryRouteWithChildren,
  TrainerRoute: TrainerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
